darkMode: "auto"
colorBy: "series"
color:
  0: "#5470c6"
  1: "#91cc75"
  2: "#fac858"
  3: "#ee6666"
  4: "#73c0de"
  5: "#3ba272"
  6: "#fc8452"
  7: "#9a60b4"
  8: "#ea7ccc"
gradientColor:
  0: "#f6efa6"
  1: "#d88273"
textStyle:
  fontFamily: "sans-serif"
  fontSize: 12
  fontStyle: "normal"
  fontWeight: "normal"
stateAnimation:
  duration: 300
  easing: "cubicOut"
animation: "auto"
animationDuration: 1000
animationDurationUpdate: 500
animationEasing: "cubicInOut"
animationEasingUpdate: "cubicInOut"
animationThreshold: 2000
progressiveThreshold: 3000
progressive: 400
hoverLayerThreshold: 3000
useUTC: false
axisPointer:
  0:
    show: "auto"
    zlevel: 0
    z: 50
    type: "line"
    snap: false
    triggerTooltip: true
    value: null
    status: null
    animation: null
    animationDurationUpdate: 200
    lineStyle:
      color: "#B9BEC9"
      width: 1
      type: "dashed"
    shadowStyle:
      color: "rgba(210,219,238,0.2)"
    label:
      show: true
      formatter: null
      precision: "auto"
      margin: 3
      color: "#fff"
      padding:
        0: 5
        1: 7
        2: 5
        3: 7
      backgroundColor: "auto"
      borderColor: null
      borderWidth: 0
      borderRadius: 3
    handle:
      show: false
      icon: "M10.7,11.9v-1.3H9.3v1.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4h1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7v-1.2h6.6z M13.3,22H6.7v-1.2h6.6z M13.3,19.6H6.7v-1.2h6.6z"
      size: 45
      margin: 50
      color: "#333"
      shadowBlur: 3
      shadowColor: "#aaa"
      shadowOffsetX: 0
      shadowOffsetY: 2
      throttle: 40
tooltip:
  0:
    position: "top"
    zlevel: 0
    z: 60
    show: true
    showContent: true
    trigger: "item"
    triggerOn: "mousemove|click"
    alwaysShowContent: false
    displayMode: "single"
    renderMode: "auto"
    confine: null
    showDelay: 0
    hideDelay: 100
    transitionDuration: 0.4
    enterable: false
    backgroundColor: "#fff"
    shadowBlur: 10
    shadowColor: "rgba(0, 0, 0, .2)"
    shadowOffsetX: 1
    shadowOffsetY: 2
    borderRadius: 4
    borderWidth: 1
    padding: null
    extraCssText: ""
    axisPointer:
      type: "line"
      axis: "auto"
      animation: "auto"
      animationDurationUpdate: 200
      animationEasingUpdate: "exponentialOut"
      crossStyle:
        color: "#999"
        width: 1
        type: "dashed"
      textStyle:
    textStyle:
      color: "#666"
      fontSize: 14
yAxis:
  0:
    type: "category"
    data:
      0: "08: 00"
      1: "08: 30"
      2: "09: 30"
      3: "10: 30"
      4: "11: 30"
      5: "14: 30"
      6: "15: 30"
      7: "16: 30"
      8: "17: 30"
      9: "19: 30"
      10: "20: 30"
      11: "21: 30"
      12: "22: 30"
    splitArea:
      show: true
      areaStyle:
        color:
          0: "rgba(250,250,250,0.2)"
          1: "rgba(210,219,238,0.2)"
    boundaryGap: true
    deduplication: null
    splitLine:
      show: false
      lineStyle:
        color:
          0: "#E0E6F1"
        width: 1
        type: "solid"
    axisTick:
      alignWithLabel: false
      interval: "auto"
      show: true
      inside: false
      length: 5
      lineStyle:
        width: 1
    axisLabel:
      interval: "auto"
      show: true
      inside: false
      rotate: 0
      showMinLabel: null
      showMaxLabel: null
      margin: 8
      fontSize: 12
    show: true
    zlevel: 0
    z: 0
    inverse: false
    name: ""
    nameLocation: "end"
    nameRotate: null
    nameTruncate:
      maxWidth: null
      ellipsis: "..."
      placeholder: "."
    nameTextStyle:
      nameGap: 15
      silent: false
      triggerEvent: false
      tooltip:
        show: false
      axisPointer:
      axisLine:
        show: true
        onZero: true
        onZeroAxisIndex: null
        lineStyle:
          color: "#6E7079"
          width: 1
          type: "solid"
        symbol:
          0: "none"
          1: "none"
        symbolSize:
          0: 10
          1: 15
    offset: 0
xAxis:
  0:
    type: "category"
    data:
      0: "星期一"
      1: "星期二"
      2: "星期三"
      3: "星期四"
      4: "星期五"
      5: "星期六"
    splitArea:
      show: true
      areaStyle:
        color:
          0: "rgba(250,250,250,0.2)"
          1: "rgba(210,219,238,0.2)"
    boundaryGap: true
    deduplication: null
    splitLine:
      show: false
      lineStyle:
        color:
          0: "#E0E6F1"
        width: 1
        type: "solid"
    axisTick:
      alignWithLabel: false
      interval: "auto"
      show: true
      inside: false
      length: 5
      lineStyle:
        width: 1
    axisLabel:
      interval: "auto"
      show: true
      inside: false
      rotate: 0
      showMinLabel: null
      showMaxLabel: null
      margin: 8
      fontSize: 12
    show: true
    zlevel: 0
    z: 0
    inverse: false
    name: ""
    nameLocation: "end"
    nameRotate: null
    nameTruncate:
      maxWidth: null
      ellipsis: "..."
      placeholder: "."
    nameTextStyle:
    nameGap: 15
    silent: false
    triggerEvent: false
    tooltip:
      show: false
    axisPointer:
    axisLine:
      show: true
      onZero: true
      onZeroAxisIndex: null
      lineStyle:
        color: "#6E7079"
        width: 1
        type: "solid"
      symbol:
        0: "none"
        1: "none"
      symbolSize:
        0: 10
        1: 15
    offset: 0
grid:
  0:
    height: "50%"
    top: "10%"
    show: false
    zlevel: 0
    z: 0
    left: "10%"
    right: "10%"
    containLabel: false
    backgroundColor: "rgba(0,0,0,0)"
    borderWidth: 1
    borderColor: "#ccc"
series:
  0:
  name: "Punch Card"
  type: "heatmap"
  data:
    0:
      0: 0
      1: 0
      2: 5
  label:
    show: true
  emphasis:
    itemStyle:
      shadowBlur: 10
      shadowColor: "rgba(0, 0, 0, 0.5)"
    label:
      show: true
  coordinateSystem: "cartesian2d"
  zlevel: 0
  z: 2
  geoIndex: 0
  blurSize: 30
  pointSize: 20
  maxOpacity: 1
  minOpacity: 0
  select:
    itemStyle:
      borderColor: "#212121"
visualMap:
  0:
    min: 0
    max: 10
    calculable: true
    orient: "horizontal"
    left: "center"
    bottom: "15%"
    show: true
    zlevel: 0
    z: 4
    seriesIndex: "all"
    right: null
    top: null
    itemWidth: null
    itemHeight: null
    inverse: false
    backgroundColor: "rgba(0,0,0,0)"
    borderColor: "#ccc"
    contentColor: "#5793f3"
    inactiveColor: "#aaa"
    borderWidth: 0
    padding: 5
    textGap: 10
    precision: 0
    textStyle:
      color: "#333"
    align: "auto"
    hoverLink: true
    realtime: true
    handleIcon: "path://M-11.39,9.77h0a3.5,3.5,0,0,1-3.5,3.5h-22a3.5,3.5,0,0,1-3.5-3.5h0a3.5,3.5,0,0,1,3.5-3.5h22A3.5,3.5,0,0,1-11.39,9.77Z"
    handleSize: "120%"
    handleStyle:
      borderColor: "#fff"
      borderWidth: 1
    indicatorIcon: "circle"
    indicatorSize: "50%"
    indicatorStyle:
      borderColor: "#fff"
      borderWidth: 2
      shadowBlur: 2
      shadowOffsetX: 1
      shadowOffsetY: 1
      shadowColor: "rgba(0,0,0,0.2)"
    target:
      inRange:
        color:
          0: "#f6efa6"
          1: "#d88273"
          2: "#bf444c"
      outOfRange:
        color:
          0: "rgba(0,0,0,0)"
        opacity:
          0: 0
          1: 0
    controller:
      inRange:
        color:
          0: "#f6efa6"
          1: "#d88273"
          2: "#bf444c"
        symbol:
          0: "roundRect"
        symbolSize:
          0: 20
          1: 20
      outOfRange:
        color:
          0: "#aaa"
        symbol:
          0: "roundRect"
        symbolSize:
          0: 20
          1: 20
    range:
      0: 0
      1: 10
